feat: [PL-22078]: New files coverage check script
harness/jarvis pull request #13
Opened 2022-01-27 08:12 UTC by avinashmadhwani02

2022-01-27 08:40 UTC, vkbansal requested changes

2022-01-27 08:40 UTC, vkbansal commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +  const jsonReport = await $`cat coverage/coverage-summary.json`;
Take this also as a command line argument and read it using `fs.promises.readFile`

2022-01-27 08:40 UTC, vkbansal commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +  const newFilesAdded = splitted.filter(filterFiles);
you can take globs as CLI arguments and use `multimatch` package to filter files

2022-01-27 08:40 UTC, vkbansal commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +      const fileReport = JSON.parse(`${jsonReport}`)[fullFilePath];
You are parsing this everytime. This should be done only once

2022-01-27 08:40 UTC, vkbansal commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +          if (fileReport[prop].pct < (options.threshold || 80)) {
use default value in yargs rather than doing it here. Also will not work with 0

2022-01-27 16:01 UTC, vkbansal commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +      console.log(chalk.red(`file ${fileName} not considered/covered for/in test cases`));
I think that a lot of information is being logged to console, making it unhelpful in long run. We can put this behind a `--verbose` flag.

2022-01-27 16:02 UTC, vkbansal commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +    return multimatch(splitted, ['**', '!**/*.test.tsx', '!**/*.test.ts', '!**/*.snap', '!**/*.scss', '!**/*.js', '!']);
Take the globs from CLI itself. yargs has an option for array.

2022-01-27 16:03 UTC, vkbansal commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +      for (const prop in fileReport) {
Probably using `Array.filter` would be better option.

2022-01-28 05:15 UTC, avinashmadhwani02 commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +      for (const prop in fileReport) {
fileReport is an object, and I have used `break` if the coverage fails.

2022-01-28 06:58 UTC, vkbansal requested changes

2022-01-28 06:58 UTC, vkbansal commented on bin/new-files-coverage-check.js
> +          alias: 'ext',
```suggestion
          alias: 'exclude',
```

2022-01-28 06:58 UTC, vkbansal commented on bin/new-files-coverage-check.js
> +          describe: 'The extensions to ignore for. Example: .css, .scss',
```suggestion
          describe: 'Globs to ignore for. Example: *.test.ts, *.test.tsx',
```

2022-01-28 06:58 UTC, vkbansal commented on bin/new-files-coverage-check.js
> +          default: ['!**/*.test.tsx', '!**/*.test.ts', '!**/*.snap', '!**/*.scss', '!**/*.js', '!']
```suggestion
          default: ['!**/*.test.tsx', '!**/*.test.ts', '!**/*.snap']
```

2022-01-28 06:58 UTC, vkbansal commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +      for (const prop in fileReport) {
My Bad. I meant at line 40
```
const failedFiles = files.filter(file => /* return true if coverage is less than 80*/)
```

2022-01-28 07:28 UTC, avinashmadhwani02 commented on bin/new-files-coverage-check.js
> +          default: ['!**/*.test.tsx', '!**/*.test.ts', '!**/*.snap', '!**/*.scss', '!**/*.js', '!']
why are we removing .scss and .js?

2022-01-28 10:59 UTC, vkbansal commented on bin/new-files-coverage-check.js
> +          default: ['!**/*.test.tsx', '!**/*.test.ts', '!**/*.snap', '!**/*.scss', '!**/*.js', '!']
This is an open source package and we should add generic defaults and not specific to our use case

2022-01-31 08:39 UTC, vkbansal commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +    const files = await $`git diff ${baseBranch} --name-status | grep '^A' | cut -c 3-`;
Sanitization is our responsibility

2022-02-01 05:30 UTC, avinashmadhwani02 commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +    const files = await $`git diff ${baseBranch} --name-status | grep '^A' | cut -c 3-`;
Any suggestions on how to sanitize the branch names? Should we add this [regex](https://stackoverflow.com/questions/12093748/how-do-i-check-for-valid-git-branch-names) in `yargs` while taking branch as input?

2022-02-02 06:34 UTC, abhinavrastogi-harness approved these changes

2022-02-02 08:35 UTC, vkbansal approved these changes

2022-02-02 08:39 UTC, merged