feat: [PL-22665]: Using Git API to fetch changed files in a pull request
harness/jarvis pull request #15
Opened 2022-02-15 08:32 UTC by avinashmadhwani02

2022-02-15 08:35 UTC, vkbansal requested changes

2022-02-15 08:35 UTC, vkbansal commented on bin/new-files-coverage-check
> +          default: 'harness'
do not give default for this

2022-02-15 08:37 UTC, avinashmadhwani02 commented on bin/new-files-coverage-check
> +          default: 'harness'
Organisation is going to be `harness` always right? if not user can override it. Any reason for this change?

2022-02-15 09:43 UTC, abhinavrastogi-harness commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +import { $, fetch } from 'zx';
`zx` has a fetch function exported? why?

2022-02-15 09:43 UTC, abhinavrastogi-harness commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +      `https://api.github.com/repos/${owner}/${repoName}/pulls/${pull_number}/files?per_page=100`
no headers needed for token etc?

2022-02-15 09:43 UTC, abhinavrastogi-harness commented on bin/new-files-coverage-check
> +          default: 'harness'
we can combine owner into reponame.. user can give `harness/harness-core-ui` or `wings-software/wingsui` directly instead of giving then separately. you can split them on `/`.
we can add a validation that the reponame should have a `/`.
thoughts?

2022-02-15 10:45 UTC, avinashmadhwani02 commented on bin/new-files-coverage-check
> +          default: 'harness'
@abhinavrastogi-harness we can take separate values from the user if we have to anyways split and put a validation on it. 
What's the advantage of taking it as one complete string? - they are 2 different values for Git API as well

2022-02-15 10:47 UTC, avinashmadhwani02 commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +import { $, fetch } from 'zx';
It supports fetch

<img width="1052" alt="Screenshot 2022-02-15 at 4 16 25 PM" src="https://user-images.githubusercontent.com/62028553/154046554-632277ac-b5ff-4930-894a-b15b3a6a431a.png">

2022-02-15 10:49 UTC, avinashmadhwani02 commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +      `https://api.github.com/repos/${owner}/${repoName}/pulls/${pull_number}/files?per_page=100`
It's working without token :D

Could be because the repo is open source.

2022-02-15 11:17 UTC, vkbansal commented on bin/new-files-coverage-check
> +          default: 'harness'
Think of this as an open source tool. It should not have any specific to harness.

2022-02-15 11:17 UTC, vkbansal commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +      `https://api.github.com/repos/${owner}/${repoName}/pulls/${pull_number}/files?per_page=100`
Yes. Also it will soon hit rate limit, if token is not used. Good catch @abhinavrastogi-harness

2022-02-22 05:29 UTC, avinashmadhwani02 commented on src/jest/new-files-coverage-check/new-files-coverage-check.ts
> +      `https://api.github.com/repos/${owner}/${repoName}/pulls/${pull_number}/files?per_page=100`
Added token support

2022-02-23 11:08 UTC, vkbansal approved these changes

2022-02-23 11:32 UTC, abhinavrastogi-harness approved these changes

2022-02-23 11:39 UTC, merged